### ISSUE TITLE
The bot has an error when connecting with mongo

### ISSUE THREAD

**Issue by Pipeeee1231** [elbkr/ticket-bot#11]
![image](https://user-images.githubusercontent.com/83485167/147626050-42894884-7579-4f5c-930e-a3110d861978.png)

**Comment by elbkr** [comment]
Hi, it’s not mongo, you have to kick the bot an invite it again with the invite link I specified in the readme. Replace REPLACE_THIS with your bot’s id

**Comment by rafalohaki** [comment]
i got an error while trying to run:
```/home/autarch/dcbot/ticket-bot/node_modules/@discordjs/rest/dist/index.js:667
        throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[50035]: Invalid Form Body
options[0][UNION_TYPE_CHOICES]: Value of field "type" must be one of (3, 5, 10, 1, 2, 7, 4, 11, 8, 9, 6).
    at SequentialHandler.runRequest (/home/autarch/dcbot/ticket-bot/node_modules/@discordjs/rest/dist/index.js:667:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/autarch/dcbot/ticket-bot/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/autarch/dcbot/ticket-bot/node_modules/@discordjs/rest/dist/index.js:910:22) {```

**Comment by elbkr** [comment]
Hey, I think it's because the code is outdated. I'll update it when I have time
